version: 2.1

commands:
  setup-env:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: lein with-profile -dev,+test,+ci deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

executors:
  lein-executor:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

jobs:
  build:
    executor: lein-executor
    steps:
      - setup-env
      - run:
          name: 'Run JVM test suite'
          command: lein with-profile -dev test
      - run:
          name: 'Run JVM test suite, with utils.spec 1.1.0'
          command: lein with-profile -dev,+utils.spec-1.1.0 test
      - run:
          name: 'Run JVM test suite, failing on reflection warnings'
          command: lein with-profile -dev,+warn-on-reflection test 2>&1 | grep warning && exit 1 || exit 0
      - run:
          name: 'Ensure production isolation'
          command: lein with-profile -dev,+check check
      - run:
          name: 'Compile ClojureScript test suite'
          command: lein with-profile -dev,+test do clean, cljsbuild once test
      - run:
          name: 'Run node.js tests'
          command: node target/out/tests.js
      - run:
          name: 'Compile ClojureScript test suite, with utils.spec 1.1.0'
          command: lein with-profile -dev,+test,+utils.spec-1.1.0 do clean, cljsbuild once test
      - run:
          name: 'Run node.js tests, with utils.spec 1.1.0'
          command: node target/out/tests.js
  deploy:
    executor: lein-executor
    steps:
      - setup-env
      - run:
          name: import GPG key
          command: echo -e "$GPG_KEY_V2" | gpg --import
      - run:
          name: Perform pre-release sanity check
          command: lein with-profile -dev,+ci,+ncrw run -m nedap.ci.release-workflow.api sanity-check
      - run:
          name: release to Clojars
          command: lein deploy clojars

workflows:
  version: 2
  CircleCI:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-alpha\d+)?$/
      - deploy:
          context:
            - Clojars
            - GPG
            - Github
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-alpha\d+)?$/
